// src/resources/assets/js/components/State.vue
<template>
    <span :class="'label label-'+color">
        {{ state }}
    </span>
</template>

<script>
    export default {
        props: ['state'],

        computed: {
            color() {
                if (this.state == 'running')
                {
                    return 'info';
                }
                else if (this.state == 'ok')
                {
                    return 'success';
                }
                else if (this.state == 'failed')
                {
                    return 'danger';
                }

                return 'default';
            }
        },
    }
</script>

// src/resources/views/javascript/state.jsx
// ------------------------------------------------
// ---- State

var State = React.createClass({
    render: function()
    {
        var color;

        if (this.props.type == 'running')
        {
            color = 'info';
        }
        else if (this.props.type == 'ok')
        {
            color = 'success';
        }
        else if (this.props.type == 'failed')
        {
            color = 'danger';
        }
        else if (this.props.type == 'queued')
        {
            color = 'default';
        }

        return (
            <span className={"label label-"+color}>{this.props.type}</span>
        );
    }
});
